title: Basmah Qenab
logo: https://basmaqenab.github.io/Untitled design.png 
description: Dedicated to merging healthcare expertise with data-driven insights, fostering impactful change through meticulous analysis. Credly account [here](https://www.credly.com/users/basma-qenab)
theme: jekyll-theme-minimal
