title: Basmah Qenab
logo: https://basmaqenab.github.io/Untitled design.png 
description: Dedicated to merging healthcare expertise with data-driven insights, fostering impactful change through meticulous analysis
theme: jekyll-theme-minimal
[Linkedin](https://www.linkedin.com/in/basma-qenab-198ba279/)
