title: Basmah Qenab
logo: https://basmaqenab.github.io/pic2025.jpg
description: Dedicated to merging healthcare expertise with data-driven insights, fostering impactful change through meticulous analysis. 
theme: jekyll-theme-minimal
